name: aws access
description:  authenticate aws
inputs:
  access:
    description:  AWS_ACCESS_KEY_ID
    required: true
  secret:
    description: AWS_SECRET_ACCESS_KEY
    required: true
  region:
    description: region
    default: "us-east-1"


runs:
  using: "composite"
  steps: 
    - name: access
      shell: bash
      run: |
        export AWS_ACCESS_KEY_ID=${{ inputs.access }}
        export AWS_SECRET_ACCESS_KEY=${{ inputs.secret }}
        AWS_REGION=${{ inputs.region }}
        aws sts get-caller-identity
       