name: cat file
description: list content file
inputs:
  path:
    description: enter a file name to cat 
    required: true
    default: "note.txt"


runs:
    using: "composite"
    steps: 
       - name: step1
         shell: bash
         run: |
           cat ${{ inputs.path }}

      #  - name: step2
      #    shell: bash
      #    run: ls

      #  - name: step3
      #    shell: bash
      #    run:  cat README.md 
