name: cat file
description: list content file



runs:
    using: "composite"
    steps: 
       - name: step1
         shell: bash
         run: |
           cat note.txt

       - name: step2
         shell: bash
         run: ls

       - name: step3
         shell: bash
         run:  cat README.md 
