name: "List Directories"
description: "Custom action to list directories in a given path"
inputs:
  path:
    description: "Directory path to list"
    required: true
    default: "Dockerfile"
runs:
  using: "composite"
  steps:
    - name: cat Dockerfile
      shell: bash
      run: |
        echo "cat in ${{ inputs.path }}:"
        cat ${{ inputs.path }}
