name: "AWS Auth"
description: "Authenticate with AWS using secrets"
inputs:
  aws-access-key-id:
    description: "access key"
    required: true
  aws-secret-access-key:
    description: "secret key"
    required: true
  aws-region:
    description: "region"  
    required: true
    default: "us-east-1"
runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      shell: bash
      run: |
        export AWS_ACCESS_KEY_ID=${{ inputs.aws-access-key-id }}
        export AWS_SECRET_ACCESS_KEY=${{ inputs.aws-secret-access-key }}
        export AWS_REGION=${{ inputs.aws-region }}
        aws sts get-caller-identity
