name: aws authenticate
  
on:
    push:
        branches: ["master"]

jobs:
    custom1:
        runs-on: ubuntu-latest
        steps:
            - name: check
              uses: actions/checkout@v6

            - name: use custom action
              uses: ./.github/actions/awsauth
              with:
                aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1   