name: schedule



on: 
    schedule: 
        - cron: "0 */2 * * *"     
    
    workflow_dispatch:    
    

jobs:
    schedule:
        runs-on: ubuntu-latest
        steps: 
            - name: list
              run: ls
