name: custom action 1 
  
on:
    push:
        branches: ["master"]

jobs:
    custom1:
        runs-on: ubuntu-latest
        steps:
            - name: check
              uses: actions/checkout@v6

            - name: use custom action
              uses: ./.github/actions/cat
              with:
                path: custom1