name: custom action1
on:
   push:
    branches: ["master"]
    
jobs:    
  say-hello:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v6

        - name: use custom action
          uses: ./.github/actions/awsauth
          with:
            access: ${{ secrets.aws_access }}
            secret: ${{ secrets.aws_secret }}
            # region: ""    