name: echo hello
on:
  push:
    branches:
      - master
    # paths:
    #   - ".github/**"
    # paths-ignore:
    #   - ".github/**"
  pull_request:
    types:
      - opened
    branches:
      - master   
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
    - name: say hello
      run: echo "Hello, GitHub Actions!"      
    - name: say goodbye
      run: echo "GoodBye, GitHub Actions!"     
      
  ls:
    runs-on: ubuntu-latest
    steps:
    - name: run ls
      run: ls
# -------------------      
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run ls again
      run: ls 
# -----------------
    - name: Make dep.sh executable
      run: chmod +x ./dep.sh
    - name: deploy script
      run: ./dep.sh
