name: echo hello
on:
  push:
    branches:
      - master
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
    - name: say hello
      run: echo "Hello, GitHub Actions!"      
    - name: say goodbye
      run: echo "GoodBye, GitHub Actions!"     
      
