name: echo hello
on:
  issues:
    types: opened
 
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: show issue content
      run: echo '${{github.event}}' | jq
