name: echo hello
on:
  issues:
    types: opened
 
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
    - name: show issue content
      run: echo '${{toJson(github.event)}}'
    - name: show specific value into event
      run: echo "${{ github.event.issue.repository_url }}"
