name: this workflow is to print hello

on:
  push: 
    branches: ['master']


jobs:
    say_hello: 
        runs-on: ubuntu-latest
        steps:
            - name: say hello 
              run: echo "hello ya abanoub"
            - name: say goodby
              run: echo "goodbye ya abanoub"              