name: this workflow is to print hello

on:
  push: 
    branches: 
        - master
        - main


jobs:
    say_hello: 
        runs-on: ubuntu-latest
        steps:
            - name: say hello 
              run: echo "hello ya abanoub"
            - name: say goodby
              run: echo "goodbye ya abanoub" 
    time:
        runs-on: ubuntu-latest
        steps:
            - name: time now 
              run: |
                date
                date +"%Y"      
                TZ="Africa/Cairo" date
    
    list:
        runs-on: ubuntu-latest
        steps:
            - name: git clone
              uses: actions/checkout@v6

            - name: ls
              run: | 
                 ls -l               