name: pass output 

on: 
    push:
        branches: ["master"]

jobs: 
    demo:
        runs-on: ubuntu-latest
        steps: 
        # - name: git clone  repo
        #   uses: actions/checkout@v6

        - name:   cat file
          run: |
             cat hello
            

