name: show issue content

on:
  issues: 
    types:  opened


jobs:
    reserved-wprds:
        runs-on: ubuntu-latest
        steps:
            - name: git clone
              uses: actions/checkout@v6
            
            - name: show issue content
              run: echo "${{ toJson(github.event) }}"


            - name: show repo name
              run : echo ${{ github.repository }}   
             
            - name: show repo name
              run : echo ${{ github.repository_owner }}                 
