name: Pass Output Example

on:
  push:
    branches: [ "master" ]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: List directories
        id: cat
        shell: bash
        run: |
          dirs=$(cat Dockerfile)
          echo "words=$dirs" >> $GITHUB_OUTPUT

      - name: Use directories output
        run: | 
          echo "cat are: ${{ steps.cat.outputs.words }}"
