name: Pass Output Example

on:
  workflow_dispatch:
    inputs:
      GREETING:
        description: "Greeting message"
        default: "welcome ya 3am"
        required: true
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
# -------------------------

      - name: Show inputs
        run: | 
           echo "Greeting is: ${{ inputs.GREETING }}"
       
      - name: Show inputs
        if: "${{ inputs.GREETING == 'welcome ya 3am' }}"
        run: | 
           echo "passed"                    