name: print hello

on:
    push:
        branches:
            - master

jobs:
    print_hello:   
       runs-on: ubuntu-latest
       steps:
         - name: print hello
           run: echo "hello,from the first workflow"
         - name: print goodbye  
           run: echo "goodbye"    
         