name: print hello

on:
   issues:
      types: opened 

jobs:
    ci:   
       runs-on: ubuntu-latest
       steps:
         - name: print hello
           run: echo "hello,from the first workflow"
         - name: print goodbye  
           run: echo "goodbye"
          
    cd:
        runs-on: ubuntu-latest
        steps:
            - name: git clone
              uses: actions/checkout@v6
            #   with:
            #       repository: 'https://github.com/AbanobAyad22/kubernetes-course.git'
            - name: give permission
              run: chmod +x ./devops.sh
            - name: ls
              run: ls -la  
            - name: run script
              run: ./devops.sh
