name: print hello

on:
    push:
      branches:
        - master
      #   paths: 
      #     - ".github/**"
      #   paths-ignore: 
      #     - ".github/**"  
    pull_request:
        types: [opened,closed]
            # - opened
            # - closed
    schedule:
        - cron: "*/5 1 * * *" 
    workflow_dispatch:           


jobs:
    ci:   
       runs-on: ubuntu-latest
       steps:
         - name: print hello
           run: echo "hello,from the first workflow"
         - name: print goodbye  
           run: echo "goodbye"
          
    cd:
        runs-on: ubuntu-latest
        steps:
            - name: git clone
              uses: actions/checkout@v6
            #   with:
            #       repository: 'https://github.com/AbanobAyad22/kubernetes-course.git'
            - name: give permission
              run: chmod +x ./devops.sh
            - name: ls
              run: ls -la  
            - name: run script
              run: ./devops.sh

    get-date:    
        runs-on: ubuntu-latest
        steps:
            - name: show all github events
              run: echo '${{ toJson(github.event) }}'

            - name: show issue number
              run: echo "${{ github.event.issue.number }}"  
            - name: show issue number
              run: echo "${{ github.event.issue.body }}"                
