name: show some result

#events
on:
    issues:
        types: 
            - opened
            - closed

jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - name: hello
              run: |
                echo "${{ github.actor }}" 
                echo "${{ github.repository }}" 
                echo "${{ github.repository_owner }}" 