name: show some result

#events
on:
   push:
    branches:
        - master
    # paths:
    #     - ".github/**"     
    paths-ignore:
        - ".github/**"

jobs:
    say-hello:
        runs-on: X64
        steps:
            - name: hello
              run: |
                echo "who-is-run-this-workflow=${{ github.actor }}" 
                echo "name-of-repo=${{ github.repository }}" 
                echo "repo-owner=${{ github.repository_owner }}" 

            - name: show all event
              run: echo "${{ toJson(github.event) }}"   
            - name: show specific result
              run: |
                echo "body=${{ github.event.issue.body }}"   
                echo "title=${{ github.event.issue.title }}"
