name: show some result

#events
on:
    issues:
        types: 
            - opened
            - closed

jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - name: hello
              run: |
                echo "who-is-run-this-workflow=${{ github.actor }}" 
                echo "name-of-repo=${{ github.repository }}" 
                echo "repo-owner=${{ github.repository_owner }}" 

            - name: show all event
              run: echo "${{ toJson(github.event) }}"   
            - name: show specific result
              run: |
                echo "body=${{ github.event.issue.body }}"   
                echo "title=${{ github.event.issue.title }}"
