name: delete user 

on:
   push:
    branches: ["master"]
    
jobs:    
  say-hello:
    runs-on: ubuntu-latest
    steps:
        - name: print
          id: num 
          run: |
            num=5
            value=$(cat note.txt)
            echo "NUMBER=$num"  >> $GITHUB_OUTPUT
            echo "val=$value"  >> $GITHUB_OUTPUT

        - name: print previous step value
          run: echo ${{ steps.num.outputs.NUMBER }}  
