name: delete user 

on:
   push:
    branches: ["master"]
    
jobs:    
  say-hello:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v6
        - name: print
          id: num 
          run: |
            num=5
            hello=$(cat note.txt | tr '\n' ' ')
            echo "NUMBER=$num"  >> $GITHUB_OUTPUT
            echo "VAL=$hello"  >> $GITHUB_OUTPUT

        - name: print previous step value
          if: "${{ steps.num.outputs.NUMBER == '2' }}"
          run: |
            echo ${{ steps.num.outputs.NUMBER }}
            echo "${{ steps.num.outputs.VAL }}"

