name: first workflow 

#events
on:
    push:
        branches:
            - master

jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - name: hello
              run: echo "hello ya abanoub"  
            - name: goodbye
              run: echo "goodbye"   
            - name: error
              if: always()
              run: echo "hello again"   

# -----------------------
    # say-goodbye:
    #     runs-on: ubuntu-latest
    #     steps:    
    #         - name: say goodbye
    #           run: echo "Bye"               