name: first workflow 

#events
on:
    push:
        branches:
            - master

jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - name: hello
              run: echo "hello ya abanoub"  
            - name: goodbye
              run: echo "goodbye"   
            - name: error
              if: always()
              run: echo "hello again"   

# -----------------------
    say-goodbye:
        runs-on: ubuntu-latest
        steps:    
            - name: git clone 
              run: git clone https://github.com/AbanobAyad22/github.git
            - name: change directory
              run: cd github
            - name: list repo 
              run: ls          